# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kostek/Documents/Programming/dissertation-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kostek/Documents/Programming/dissertation-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kostek/Documents/Programming/dissertation-project/CMakeFiles /home/kostek/Documents/Programming/dissertation-project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kostek/Documents/Programming/dissertation-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ids-dissertation

# Build rule for target.
ids-dissertation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ids-dissertation
.PHONY : ids-dissertation

# fast build rule for target.
ids-dissertation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ids-dissertation.dir/build.make CMakeFiles/ids-dissertation.dir/build
.PHONY : ids-dissertation/fast

src/PacketCapture.o: src/PacketCapture.cpp.o
.PHONY : src/PacketCapture.o

# target to build an object file
src/PacketCapture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ids-dissertation.dir/build.make CMakeFiles/ids-dissertation.dir/src/PacketCapture.cpp.o
.PHONY : src/PacketCapture.cpp.o

src/PacketCapture.i: src/PacketCapture.cpp.i
.PHONY : src/PacketCapture.i

# target to preprocess a source file
src/PacketCapture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ids-dissertation.dir/build.make CMakeFiles/ids-dissertation.dir/src/PacketCapture.cpp.i
.PHONY : src/PacketCapture.cpp.i

src/PacketCapture.s: src/PacketCapture.cpp.s
.PHONY : src/PacketCapture.s

# target to generate assembly for a file
src/PacketCapture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ids-dissertation.dir/build.make CMakeFiles/ids-dissertation.dir/src/PacketCapture.cpp.s
.PHONY : src/PacketCapture.cpp.s

src/Sniffer.o: src/Sniffer.cpp.o
.PHONY : src/Sniffer.o

# target to build an object file
src/Sniffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ids-dissertation.dir/build.make CMakeFiles/ids-dissertation.dir/src/Sniffer.cpp.o
.PHONY : src/Sniffer.cpp.o

src/Sniffer.i: src/Sniffer.cpp.i
.PHONY : src/Sniffer.i

# target to preprocess a source file
src/Sniffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ids-dissertation.dir/build.make CMakeFiles/ids-dissertation.dir/src/Sniffer.cpp.i
.PHONY : src/Sniffer.cpp.i

src/Sniffer.s: src/Sniffer.cpp.s
.PHONY : src/Sniffer.s

# target to generate assembly for a file
src/Sniffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ids-dissertation.dir/build.make CMakeFiles/ids-dissertation.dir/src/Sniffer.cpp.s
.PHONY : src/Sniffer.cpp.s

src/check_dependencies.o: src/check_dependencies.cpp.o
.PHONY : src/check_dependencies.o

# target to build an object file
src/check_dependencies.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ids-dissertation.dir/build.make CMakeFiles/ids-dissertation.dir/src/check_dependencies.cpp.o
.PHONY : src/check_dependencies.cpp.o

src/check_dependencies.i: src/check_dependencies.cpp.i
.PHONY : src/check_dependencies.i

# target to preprocess a source file
src/check_dependencies.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ids-dissertation.dir/build.make CMakeFiles/ids-dissertation.dir/src/check_dependencies.cpp.i
.PHONY : src/check_dependencies.cpp.i

src/check_dependencies.s: src/check_dependencies.cpp.s
.PHONY : src/check_dependencies.s

# target to generate assembly for a file
src/check_dependencies.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ids-dissertation.dir/build.make CMakeFiles/ids-dissertation.dir/src/check_dependencies.cpp.s
.PHONY : src/check_dependencies.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ids-dissertation.dir/build.make CMakeFiles/ids-dissertation.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ids-dissertation.dir/build.make CMakeFiles/ids-dissertation.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ids-dissertation.dir/build.make CMakeFiles/ids-dissertation.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ids-dissertation"
	@echo "... src/PacketCapture.o"
	@echo "... src/PacketCapture.i"
	@echo "... src/PacketCapture.s"
	@echo "... src/Sniffer.o"
	@echo "... src/Sniffer.i"
	@echo "... src/Sniffer.s"
	@echo "... src/check_dependencies.o"
	@echo "... src/check_dependencies.i"
	@echo "... src/check_dependencies.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

